RandyKnapp/ValheimMods

EquipmentAndQuickSlots/InventoryGui_Patch.cs

We must check the equipment type for the character's inventory, not for chests, boats, carts, etc.
Closes #9

Bugfix for custom container sizes mod

---

EpicLoot/MagicItemEffects/AddLifeSteal.cs
EpicLoot/MagicItemEffects/Paralyze.cs

Fixes issue #137
Patching virtual/empty method `Character.OnDamaged()` causes crashes on linux (most likely also on mac since both use mono).
Original code was also patching `Humanoid.OnDamaged()` which is Character method override.
This patch makes Harmony patch of non-virtual `Character.Damage()` instead of above two methods.

Fix lifesteal crash on Mac/Linux

---

EquipmentAndQuickSlots/Tombstone_Fix.cs

AFAICT, using container height/width won't actually break anything with how EAQS sets height/width on the prefab (so a new release should be unnecessary), but this is more correct as it is technically possible for the inventory dimensions to not match the container's.

Use tombstone inventory height instead of container height.

---

EquipmentAndQuickSlots/ExtendedInventory.cs
EquipmentAndQuickSlots/Humanoid_Patch.cs
EquipmentAndQuickSlots/Inventory_Patch.cs

Now items will stack to the inventory first (if an item is below maximum stack), then the quick slot bar, and if any remain will be added to inventory or (if full) quick slot bar.

[EAQS] Stack to quick bar and handle item pickup when main inventory full

---

EquipmentAndQuickSlots/Humanoid_Patch.cs

Upon trying to unequip an item with a full inventory the item stays in its slot, unequipped, and you can't interact with it until restarting.

[EAQS] Fix equipment not re-equipping when trying to unequip with full inventory.

---

EpicLoot/MagicItemEffects/Executioner.cs

This resolves an NRE in ExecutionerCheckDamage_Character_Damage_Patch when "**HitData hit**" is null.

Resolve NRE in ExecutionerCheckDamage_Character_Damage_Patch

---

EpicLoot/loottables.json

In version 0.7.0 all be ok with  "Object": "Dragon", then for some inexplicable reason, "Object" was changed to "Moder" and drop stopped working

Fix drop from Moder

---

DvergerColor/VisEquipment_Patch.cs

In random cases, Dverger Circlet causes a null exception error.
Adding in a null check on light resolves the error.
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DvergerColor.LightChanger.SetLight (UnityEngine.Light light) (at <6c1386359fb74ae08e08838392af46c2>:0)
DvergerColor.VisEquipment_AttachItem_Patch.Postfix (VisEquipment instance, UnityEngine.GameObject result, System.Int32 itemHash) (at <6c1386359fb74ae08e08838392af46c2>:0)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::AttachItem>(VisEquipment,int,int,UnityEngine.Transform,bool,bool)
VisEquipment.SetHelmetEquiped (System.Int32 hash, System.Int32 hairHash) (at <035307060cbb4b30b916cd82ebd80490>:0)
VisEquipment.UpdateEquipmentVisuals () (at …
```

Resolving a null error that can occur randomly on Dverger light.

---

DvergerColor/VisEquipment_Patch.cs
EpicLoot/Adventure/AdventureDataConfig.cs
EpicLoot/Adventure/Feature/Bounties.cs
EpicLoot/EpicLoot.cs
EpicLoot/adventuredata.json

Enabling Configuration functionality to make the Boss Bounties Gated based on Bosses killed on the server.
The default configuration is Ungated.
Can be set to show Bounties based on the Current Biome with Boss killed, or show bounties for the Next Biome. allowing bounties from the next biome to show prior to killing that biome's boss.

Gated Boss Bounties

---

EpicLoot/Adventure/Feature/Bounties.cs

Ensuring that Meadow's bounties (or whatever is the first biome) are available when NextBoss is set in config.
(cherry picked from commit ec3e529f9e6096da245c6106d346ba8c48b194d7)

Ensuring that if Ungate Next Boss is set, that first bounties are set.

---

EpicLoot/CharacterDrop_Patch.cs
EpicLoot/EpicLoot.cs

This change allows EpicLoot and CLLC to co-exist in peaceful Harmony.   Mistlands Creatures, Skeletons, Moder, and Bonemass now drop EpicLoot as expected.
The change involved ensuring that EpicLoot captures the __instance.m_dropEnabled setting prior to other mods, including CLLC from being able to modify it before execution.  Then saves it as a local variable for consumption in other places.
The issue surrounds the fact that Mistlands creatures and bosses do not have Ragdolls on death.

CLLC Compatibility Fix

---

EpicLoot/Adventure/Feature/Bosses.cs

Custom error message to alert the user that the json file hasn't been updated or is missing a boss config.
(cherry picked from commit 634cbc1d67faee2cf5e42eaecca364c3b8da86e0)

Adding in feedback to the user that adventure.json has not been updated.

---

EpicLoot/EpicLoot.cs
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/DustEpic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/DustLegendary.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/DustMagic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/DustRare.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/EssenceEpic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/EssenceLegendary.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/EssenceMagic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/EssenceRare.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/ReagentEpic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/ReagentLegendary.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/ReagentMagic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneEpic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneLegendary.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneMagic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneRare.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/ShardEpic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/ShardLegendary.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/ShardMagic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/ShardRare.prefab

Removes the logic for deriving the Rarity name from a Config value and standardizes on using the Localized string.  Also includes Unity changes that update the names of the items.
(cherry picked from commit eedda08121ecf894684153f10912d0a850954b83)

Localized Item Asset Names

---

ValheimUnity/AssetBundles/epicloot.manifest
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneEpic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneLegendary.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneMagic.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneRare.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/Equipment/Andvaranaut.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/Equipment/GoldRubyRing.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/Equipment/LeatherBelt.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/Equipment/LegendarySword1.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/Equipment/SilverRing.prefab

Runestones, Andarvarant, Rings, and Belts, now are able to be picked up off the ground without interacting with them.
(cherry picked from commit ed32d02ac73105250107595efb040f9d28e646b2)

Fixing Ability to pick up Runestones and Equipment from the ground when spawned or dropped.

---

EpicLoot/EpicLoot.csproj
EpicLoot/GatedItemType/GatedItemTypeHelper.cs
EpicLoot/iteminfo.json

The Gating system now allows either a specific item or another group as the Fallback value.
In the event that it's a group, it will chain fallbacks and keep track to ensure no recursive loops can occur in the config (should someone absolutely evil decide to be a monster).  (aka... Staffs fall back to Fists, which fall back to Staffs, and hilarity ensues)
(cherry picked from commit c275b0f37f8f3bc8b4dae0a43c3a1b228771cb11)

Updated Item Gating to allow more variety instead of just Clubs.

---

EpicLoot/Terminal_Patch.cs

The terminal command Timescale was not working, and was covering up the vanilla command doing the same thing.
Removing it.
(cherry picked from commit 8f78d5ec9415e1ca7c9f638184530840f0e1771d)

Removing Timescale.

---

EpicLoot/Patching/FilePatching.cs

Allow "AppendAll" as an option which will add the array value from the patch to the array in the path target.

AppendAll Option added to configuration manager.

---

EpicLoot/MagicItemComponent.cs

Refactored Logic didn't take into consideration the difference between element count and item count.
This now circulates through the width of the Player's inventory and then matches based on the grid position, if an item isn't found, it disables the background.
Also restricting it so that Equipment Slots (and other mods) don't activate this logic.
(cherry picked from commit e3d940b857ca7ef2b1f17eb8a7ad213c54829ca7)

Fixing the Background Issue on HotKeyBar.

---

EpicLoot/Data/ConfigValue.cs
EpicLoot/EpicLoot.cs
EpicLoot/EpicLoot.csproj

Enables the Patching of Translation.json using the new Patching System.  Also ensures that translations added to the Localization dictionary are specific to EpicLoot by ensuring that mod translation name begins with "mod_epicloot_".
Fixes #468 
(cherry picked from commit 2e7ef98918eb575a9f1d526fbae11c56669c87a7)

Adding On-the-fly patching capability with Translation.json

---

EpicLoot/Crafting/AugmentTabController.cs
EpicLoot/Crafting/AugmentsAvailableDialog.cs

Adjusting Available Augments to resize if the number of augments available is longer than the provided Text box in Non-Auga UI's.
Fixes #463 
(cherry picked from commit b382c8aea4efd231e147152061bb912c8aa3bde2)

Available Effects Clipping 

---

EpicLoot/MagicItemComponent.cs

Originally we talked about removing it, but I think it's OK to leave it as is.  I've changed it to GetorCreate so that it will always return the Item back to that method (and not be null).
Part of it, is that it keeps some of that integration code in one spot for future overhaul, should it need it.  The other part of it is, that I like the simplicity of `.Extended` where used in the rest of the code.

Changing this to GetorCreate to ensure that we have an item returned.

---

EpicLoot/Data/EIDFLegacy.cs
EpicLoot/EpicLoot.cs
EpicLoot/ItemDrop_Patch_MagicItemTooltip.cs

Validates that the Crafter Name displays appropriately regardless of whether it was a prior or current EIDF item or not.
Fixes #493

Ensuring Crafter Name shows appropriately.

---

EpicLoot/MagicItemComponent.cs

This restores the background highlighting on the Quick Slot bar (or other bars in use by other mods)

Unrestricting the HotkeyBar action

---

AdvancedPortals/Teleport_Patch.cs

Problem Statement: 
Some mods use inventories that are not visible in the base game. Thus Humanoid.IsTeleportable() return undesired results.  
Solution:
By attaching onto the Inventory.IsTeleportable() method, we can inspect all inventories and apply the appropriate modifications to the result.

Ensure All Inventories are validated

---

EquipmentAndQuickSlots/InventoryGui_Patch.cs

This updates EAQS to Patch 0.214.2.
It's a small change, but they changed a method to a property, which breaks backward compatibility.

Updating EAQS for 0.214.2

---

EpicLoot/Adventure/StoreGui_Patch.cs

This came in as a community request from another mod author who's mod creates multiple different NPC "Traders" across the Valheim world.  Epic Loot was opening up on every trader NPC, instead of just Haldor.
This limits the scope of EpicLoot to only open when interacting with Haldor.

Check for Haldor in Trader object prior to opening up store.

---

EpicLoot/VisEquipment_Patch.cs

The InventoryGui.OnSelectedItem does an Unequip and an Equip when moving equipped armor around.  There's a flag that disables equipment effects so that it doesn't process changes.
Adding a check, and if TriggerEffects is false, then it's going to skip the Unequip action.

EquipFx's Turn Off When Moved In Inventory

---

DvergerColor/VisEquipment_Patch.cs

Dverger circlet contains more than one light components. When switching them on/off, apply enabled state to all light components.

Turn all of the lights in Dverger Circlet on/off

---

EquipmentAndQuickSlots/EquipmentAndQuickSlots.cs

When the keybinding in EAQS goes missing, this method doesn't return the proper value, it's not returning null, but it wasn't returning a keycode either.
string.Empty throws errors downstream.

EAQS Keybinding Issue

---

EpicLoot/Adventure/AdventureDataManager.cs
EpicLoot/Adventure/AdventureSaveData.cs
EpicLoot/Adventure/BountyTarget.cs
EpicLoot/Adventure/Feature/Bounties.cs
EpicLoot/CHANGELOG.md
EpicLoot/CharacterDrop_Patch.cs
EpicLoot/Crafting/DisenchantTabController.cs
EpicLoot/CraftingV2/EnchantingUIController.cs
EpicLoot/Data/CustomDataManager.cs
EpicLoot/EpicLoot.cs
EpicLoot/ItemDrop_Patch_MagicItemTooltip.cs
EpicLoot/LootRoller.cs
EpicLoot/MagicItemComponent.cs
EpicLoot/MagicItemEffects/FeatherFall.cs
EpicLoot/MagicItemEffects/ModifyAttackSpeed.cs
EpicLoot/MagicItemEffects/ModifyStaggerDuration.cs
EpicLoot/MagicItemEffects/Paralyze.cs
EpicLoot/MagicItemEffects/Slow.cs
EpicLoot/Properties/AssemblyInfo.cs
EpicLoot/VisEquipment_Patch.cs
EpicLoot/enchantcosts.json
EpicLoot/manifest.json

**Advanced Portals Release 1.0.5 **
```markdown
* Updated Portal Connection logic which was preventing Advanced Portals from connecting
* Updates for 0.216.9 Valheim
```
**Epic Loot 0.9.15 Official Release:**
```markdown
* Updated `enchantcosts.json` with the corrected spelling of Trophy (from Trophie).
* Fixed issue with bounties not working correctly after update to 0.9.14.
* Left a piece out that needed to be updated with regards to `CopyCustomDataFromUpgradedItem`
* This fixes the pickable issue with unlimited pickable drops.
* Required updates for Valheim version 0.216.9
```

EpicLoot and Other Mod Releases

---

AdvancedPortals/AdvancedPortals.cs
AdvancedPortals/ConnectPortals_Patch.cs
AdvancedPortals/Properties/AssemblyInfo.cs
AdvancedPortals/README.md
AdvancedPortals/manifest.json
CreatureLevelAndLootControl/API.cs
CreatureLevelAndLootControl/CreatureLevelAndLootControl.csproj
EpicLoot/Data/CustomDataManager.cs
EpicLoot/MagicItemComponent.cs
EpicLoot/MagicItemEffects/Waterproof.cs
ValheimMods.sln

**Advanced Portals Release 1.0.5 **
```markdown
* Updated Portal Connection logic which was preventing Advanced Portals from connecting
* Updates for 0.216.9 Valheim
```
**Epic Loot 0.9.15 Official Release:**
```markdown
* Updated `enchantcosts.json` with the corrected spelling of Trophy (from Trophie).
* Fixed issue with bounties not working correctly after update to 0.9.14.
* Left a piece out that needed to be updated with regards to `CopyCustomDataFromUpgradedItem`
* This fixes the pickable issue with unlimited pickable drops.
* Required updates for Valheim version 0.216.9
```

EpicLoot v0.9.15 and Advanced Portals - PR Take 2

---

EpicLoot/CHANGELOG.md
EpicLoot/Crafting/TransferMagicalEffects.cs
EpicLoot/EpicLoot.cs
EpicLoot/EpicLoot.csproj
EpicLoot/Properties/AssemblyInfo.cs
EpicLoot/manifest.json

* Recipes built with items that are Enchanted will now carry over their magical properties to the new item.
* The highest magical rarity will carry over if more than one magical item is consumed.
* Server-Synced Configuration is available toggle the enablement of this functionality.
* Default will leave this functionality Disabled.

Epic Loot 0.9.23 - Crafting with Enchanted Components
