DvergerColor/DvergerColor.cs
EpicLoot/Container_Patch.cs
EpicLoot/EpicLoot.cs
EpicLoot/EpicLoot.csproj
EpicLoot/MiniMap_Patch.cs
EpicLoot/info.md
EquipmentAndQuickSlots/EquipmentAndQuickSlots.cs
ExtendedItemDataFramework/ExtendedItemDataFramework.cs
ImprovedBuildHud/ImprovedBuildHud.cs
ItsJustWood/ItsJustWood.cs
Jam/Jam.cs
MinimalStatusEffects/MinimalStatusEffects.cs

Fixed extra item spawning near chests with rolled loot
Added harmony ID to every mod
Spawn items with random durability, not just always 100

Bugfix for EpicLoot

---

EpicLoot/EpicLoot.csproj
EpicLoot/GatedItemType/GatedItemTypeHelper.cs
EpicLoot/PlayerKnown/PlayerKnownManager.cs
EpicLoot/PlayerKnown/PlayerKnownPatches.cs
EpicLoot/ZNet_Patch.cs

Make CheckIfItemNeedsGate aware of all peers' known items/recipes.
Fixes #150

WIP: Implement syncing known items and recipes between clients and server.

---

EpicLoot/InventoryGui_Patch.cs
EquipmentAndQuickSlots/InventoryGui_Patch.cs

Fix items upgrading twice with EpicLoot and EAQS.

---

EpicLoot/Adventure/TreasureMapChest.cs
EpicLoot/EpicLoot.cs

This will resolve #199 
Added Andvaranaut ping radius as a configurable item. Tested it in game, however changing the value with ConfigurationManager did not take effect until I restarted the game.

Andvaranaut ping radius config

---

EpicLoot/Adventure/Feature/AdventureFeature.cs
EpicLoot/adventuredata.json

Enable Ocean Bounties

---

EpicLoot/LootRoller.cs
ExtendedItemDataFramework/ItemStand_Patch.cs

Fix lost item rarity for ItemStand and loot drops.

---

EquipmentAndQuickSlots/ExtendedInventory.cs
EquipmentAndQuickSlots/Inventory_Patch.cs

Removed patched GetTotalWeight override as it was redundant.
Fixed UpdateTotalWeight override to work correctly and update m_totalweight instead of returning value
Call UpdateTotalWeight appropriately when inventory is modified

Eaqs encumbered fix

---

EpicLoot/PlayerKnown/PlayerKnownManager.cs

sends to avoid timing out for players with huge modlists/lots of items

Split zRPC logic of mats / recipes into 2 separate pkg 

---

EpicLoot/magiceffects.json

https://github.com/RandyKnapp/ValheimMods/blob/41988956f321d3262d29ff49b937a56160438927/EpicLoot/translations.json#L402

Fix losted line

---

EpicLoot/Adventure/BountyTarget.cs

when it canot load the zpkg from server because server does not exist in this situation

First attempt at resolving the NRE in single player mode

---

EpicLoot/Adventure/AdventureSaveData.cs
EpicLoot/Adventure/BountyTarget.cs
EpicLoot/Adventure/Feature/Bounties.cs

I've tested this several times now and haven't run into an issue so far.  While I didn't rollback the changes that caused the original issue, I did remove the IsDedicated check in the if statements since almost all the following behavior only check if it is a server.  Let me know if you have any questions about my code, this is my first time working with a Valheim mod.

Fixed NRE on singleplayer accepted bounties

---

ValheimUnity/Assets/EpicLoot/Prefabs/Adventure/GoldBountyToken.prefab
ValheimUnity/Assets/EpicLoot/Prefabs/CraftingMaterials/RunestoneLegendary.prefab

even in the game I noticed extra text in the description of the item Gold Bounty Token

Legendary Runestone

---

ExtendedItemDataFramework/Inventory_Patch.cs

Should increase performance by a lot, especially on crowded servers.

replace gameobject instantiation with manual ItemData cloning in EIDF

---

ExtendedItemDataFramework/Inventory_Patch.cs

Reverts RandyKnapp/ValheimMods#352
Somehow this is causing serious vis equipment issues locally for me. @blaxxun-boop, hit me up on Discord and maybe we can figure this out.

Revert "replace gameobject instantiation with manual ItemData cloning in EIDF"

---

ExtendedItemDataFramework/ItemStand_Patch.cs

(cherry picked from commit ed714d2cb97ae84caa756a72d60887ce3171bd4e)
This updates EIDF InvokeRPC method with the additional argument added.  
This fixes an error when taking items off of item stands, resulting in a lag spike as well.

InvokeRPC has an updated interface.

---

ExtendedItemDataFramework/ItemStand_Patch.cs

Opps. =)  Removing test code that was left in with the previous commit.

Removing some test code that I left in there.

---

ExtendedItemDataFramework/ArmorStand_Patch.cs
ExtendedItemDataFramework/ExtendedItemDataFramework.csproj

This retains magic effects on items when taken off of armor stands.
(cherry picked from commit 1c28fb40bcb5817c93320da231a046b0687a9e0b)

Adding in EpicItem Support of Armor Stands.

---

EpicLoot/EpicLoot.csproj
ExtendedItemDataFramework/ExtendedItemDataFramework.csproj
ExtendedItemDataFramework/InventoryGui_Patch.cs

so that users of EIDF don't suffer data loss on upgrade
See:
https://github.com/RandyKnapp/ValheimMods/issues/376

Suggestion: Move Docrafting patch to EIDF 

---

EpicLoot/iteminfo.json

(cherry picked from commit e5bba69d3a187784796e0cf2fb959ba5692b2712) (cherry picked from commit 37df5dcba840431f880fdf4ac4cb8af5b6a530cd)

Moving PickAxeBlackMetal to be for goblin king.

---

EpicLoot/Adventure/AdventureDataConfig.cs
EpicLoot/Adventure/Feature/Bosses.cs
EpicLoot/Adventure/Feature/Bounties.cs
EpicLoot/adventuredata.json

(cherry picked from commit c192e08837b65ded849b321b0f4b9720e95ba80e)

Adding in configurable bosses to boss gate system

---

EpicLoot/EpicLoot.cs
EpicLoot/Patching/FilePatching.cs

Allows for patch file additions, changes, deletions, and renames on the fly without a server restart.
(cherry picked from commit e0886662e93b9820fd85887177866a6fa92bc2fa)

Patch File - Changes On The Fly

---

EpicLoot/loottables.json

(cherry picked from commit e0450d45d6b4a9b047271dff261c770fe4501830)

Adding in missing mountaincave treasure chest to loottable.

---

EpicLoot/loottables.json

Adds in Dvergers for Loot tables.

Missed Dvergers somehow.

---

EpicLoot/MagicItemComponent.cs
EpicLoot/MagicItemEffects/StaggerOnDamageTaken.cs

Minor Bug Fixes for 0.9.3

---

EpicLoot/MagicItemComponent.cs
EpicLoot/Patching/FilePatching.cs

I left out the setting to enable stacking.

Enables stacking.

---

EpicLoot/MagicItemEffectDefinitions_Setup.cs
EpicLoot/MagicItemEffects/MultiShot.cs
EpicLoot/magiceffects.json

Hi !
I thought about special effects for bows and magic staves, i make this pull request.
I thought about special effects for bows and magic staves.
So I created MultiShot.cs to handle the two new MagicEffectType (DoubleMagicShot & TripleBowShot)
I put them "NoRoll": true
to put them on unique legendary weapons or as set bonuses

Double & triple shot

---

EpicLoot/patchnotes.md

0.9.4 Release Notes

---

EpicLoot/EpicLoot.csproj
EpicLoot/Integrations/HarmonyPatches/ArmorStand_Patch.cs
EpicLoot/Integrations/HarmonyPatches/ItemStand_Patch.cs
EpicLoot/MagicItemComponent.cs

Today's Round of Bug Squashing.

Item/Armor Stands and ToolTip De-nulling

---

EpicLoot/MagicItemEffects/MultiShot.cs

If you prefer to add Triple Shot on Arbalest, you need that fix.

Add TripleShot for Arbalest

---

EpicLoot/MagicItemComponent.cs

This was failing if Local Player was null.

Local Player Bug

---

EpicLoot/MagicItemComponent.cs
EpicLoot/MagicItemEffects/FeatherFall.cs

This fixes the various status issues that we've run into.

Fixing up statuses

---

EpicLoot/EpicLoot.cs
EpicLoot/Properties/AssemblyInfo.cs
EpicLoot/README.md
EpicLoot/info.md
EpicLoot/manifest.json
EpicLoot/patchnotes.md

Updated Versioning and Patch Notes.

Release 0.9.7

---

EpicLoot/Data/EIDFLegacy.cs

So, turns out EIDF had some older type names.  This fixes that right up.

Fixes Older EIDF Crafter Names Up

---

EpicLoot/EpicLoot.cs
EpicLoot/Patching/FilePatching.cs

Now living in BepInEx/config/EpicLoot/patches folder.
Outputed JSON also go to BepInEx/config/EpicLoot folder now.
Keep Plugin Directory completely clean.

Moving Patch Folder Location

---

EpicLoot/Patching/FilePatching.cs

Epic Loot - Adds "Merge" patching action

Epic Loot - Patching Merge

---

EpicLoot/Data/CustomDataManager.cs

Converting to Lists to avoid modification errors

Update to Custom Data Manager

---

DvergerColor/DvergerColor.cs
DvergerColor/VisEquipment_Patch.cs
DvergerColor/manifest.json

#527 issues resolved in new-config generation and plugin behavior. Advanced Thunderstore manifest.json version number. Needs compilation.

Circlet patch

---

EpicLoot/patchnotes.md
EquipmentAndQuickSlots/EquipmentAndQuickSlots.cs
EquipmentAndQuickSlots/Properties/AssemblyInfo.cs

Incrementing Version Numbers and updating patch notes.

Updated EAQS to 2.1.2 and updated EL Patch Notes

---

EpicLoot/EpicLootAuga.cs

Enables Translation for Merchant Titles in new Auga 1.2.0

Updating Merchant Panel for Auga

---

EquipmentAndQuickSlots/CHANGELOG.md
EquipmentAndQuickSlots/EquipmentAndQuickSlots.cs
EquipmentAndQuickSlots/EquipmentAndQuickSlots.csproj
EquipmentAndQuickSlots/ExtendedInventory.cs
EquipmentAndQuickSlots/HotkeyBar_Patch.cs
EquipmentAndQuickSlots/InventoryGui_Patch.cs
EquipmentAndQuickSlots/PlayerExtensions.cs
EquipmentAndQuickSlots/Properties/AssemblyInfo.cs
EquipmentAndQuickSlots/README.md
EquipmentAndQuickSlots/manifest.json

* DLL packaged with 2.1.3 was incorrectly built as 2.1.2 and might not have had all the changes in it.
* Bumping version by 1 and reuploading the correct version.

EAQS Release 2.1.4

---

EquipmentAndQuickSlots/InventoryGui_Patch.cs

Minor change needed after putting all the branches together

Fixing Build after Merge conflicts.

---

AdvancedPortals/AdvancedPortal.cs
AdvancedPortals/AdvancedPortals.cs
AdvancedPortals/Properties/AssemblyInfo.cs
AdvancedPortals/README.md
AdvancedPortals/Teleport_Patch.cs
AdvancedPortals/manifest.json

* Restored Portal Connections on Dedicated Servers.

Advanced Portals 1.0.6

---

StationsAreContainers/Properties/AssemblyInfo.cs
StationsAreContainers/README.md
StationsAreContainers/StationsAreContainers.cs
StationsAreContainers/manifest.json

I've updated the call to Inventory.CountItems() to fix the Method Missing exception which happens on Hildirs Request builds of Valheim.

Updated for hildirs request.

---

ImprovedBuildHud/ImprovedBuildHud.cs
ImprovedBuildHud/Properties/AssemblyInfo.cs
ImprovedBuildHud/manifest.json

No Code Changes - Just a Rebuild and Version Bump

Improved Build Hud Release 1.0.5
